spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/twinvest
    username: twinvest
    password: twinvest

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

storage:
  root: /data/assets

worker:
  base-url: http://worker:9000

twinvest:
  simworker:
    enabled: true # closed for first stage, change to true if run the co-simulation
    baseUrl: http://localhost:8001
  storage:
    # use env var TWINVEST_STORAGE if present, else default to ./data/artifacts
    baseDir: ${TWINVEST_STORAGE:./data/artifacts}
